[package]
name = "prim-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
binrw = "0.13.3"
itertools = "0.12.1"
modular-bitfield = "0.11.2"
num-traits = "0.2.18"
obj = "0.10.2"
serde = { version = "1.0.196", features = ["derive"], optional = true }
serde_json = { version = "1.0.113" , optional = true}
bincode = "2.0.0-rc.3"
base64 = "0.21.7"
rpkg-rs = { path = "/home/dafitius/Documents/GitHub/rpkg-rs", optional = true }

[features]
default = ["rpkg"]
rpkg = ["dep:rpkg-rs"]

