[package]
name = "tex-rs"
version = "0.1.0"
edition = "2021"


[dependencies]
directxtex = "1.0.0"
binrw = "0.13.3"
bitfield-struct = "0.6.0"
lz4 = "1.24.0"
thiserror = "1.0.57"
clap = { version = "4.5.3", features = ["derive"] }
#rpkg-rs = {version= "0.1.0", optional = true}
rpkg-rs = { path = "/home/dafitius/Documents/GitHub/rpkg-rs", optional = true }

[dev-dependencies]
clap = "4.5.3"

[features]
default = ["rpkg"]
rpkg = ["dep:rpkg-rs"]